/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.formdev.flatlaf.FlatDarculaLaf;
import java.awt.Color;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author bigjo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpHappy = new javax.swing.ButtonGroup();
        outerWrapper = new javax.swing.JPanel();
        formWrapper = new javax.swing.JPanel();
        borderCenter = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFName = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblLName = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblNationality = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstNationality = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        lblSex = new javax.swing.JLabel();
        cmbSex = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        lblHappy = new javax.swing.JLabel();
        radHappyYes = new javax.swing.JRadioButton();
        radHappyNo = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        chbSecured = new javax.swing.JCheckBox();
        btnDisplay = new javax.swing.JButton();
        textAreaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        miFile = new javax.swing.JMenu();
        miFileNew = new javax.swing.JMenuItem();
        miFileOpen = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miFileClose = new javax.swing.JMenuItem();
        miFileSave = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miFileAppExit = new javax.swing.JMenuItem();
        miEdit = new javax.swing.JMenu();
        miEditCustomOutput = new javax.swing.JMenu();
        miECOPrintHappy = new javax.swing.JMenuItem();
        miECOPrintTemplate = new javax.swing.JMenu();
        miECOPTNameOnly = new javax.swing.JMenuItem();
        miECOPTAll = new javax.swing.JMenuItem();
        miEditFormToggle = new javax.swing.JMenu();
        miEFTCheckbox = new javax.swing.JCheckBoxMenuItem();
        miEFTClearOutput = new javax.swing.JMenuItem();
        miEditOutputControl = new javax.swing.JMenu();
        miEOCWhite = new javax.swing.JMenuItem();
        miEOCGreen = new javax.swing.JMenuItem();
        miEOCGreyBlack = new javax.swing.JMenuItem();
        miAbout = new javax.swing.JMenu();
        miAboutShowDialog = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Info With Menus");

        outerWrapper.setLayout(new javax.swing.BoxLayout(outerWrapper, javax.swing.BoxLayout.LINE_AXIS));

        formWrapper.setBorder(javax.swing.BorderFactory.createTitledBorder("Form"));
        formWrapper.setLayout(new java.awt.BorderLayout());

        borderCenter.setLayout(new javax.swing.BoxLayout(borderCenter, javax.swing.BoxLayout.Y_AXIS));

        lblFName.setText("First Name");
        jPanel2.add(lblFName);

        txtFName.setMinimumSize(new java.awt.Dimension(200, 24));
        txtFName.setPreferredSize(new java.awt.Dimension(170, 24));
        jPanel2.add(txtFName);

        borderCenter.add(jPanel2);

        lblLName.setText("Last Name");
        jPanel3.add(lblLName);

        txtLName.setPreferredSize(new java.awt.Dimension(170, 24));
        jPanel3.add(txtLName);

        borderCenter.add(jPanel3);

        lblNationality.setText("Nationality");
        jPanel4.add(lblNationality);

        lstNationality.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Filipino", "Japanese", "American", "British", "Korean", "Brazilian", "Vietnamese" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstNationality.setToolTipText("");
        lstNationality.setAlignmentX(1.0F);
        lstNationality.setPreferredSize(new java.awt.Dimension(170, 90));
        jScrollPane2.setViewportView(lstNationality);

        jPanel4.add(jScrollPane2);

        borderCenter.add(jPanel4);

        lblSex.setText("Sex");
        jPanel5.add(lblSex);

        cmbSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Prefer not to say" }));
        cmbSex.setPreferredSize(new java.awt.Dimension(170, 26));
        jPanel5.add(cmbSex);

        borderCenter.add(jPanel5);

        lblHappy.setText("Are you Happy?");
        jPanel6.add(lblHappy);

        btnGrpHappy.add(radHappyYes);
        radHappyYes.setText("Yes");
        jPanel6.add(radHappyYes);

        btnGrpHappy.add(radHappyNo);
        radHappyNo.setText("No");
        jPanel6.add(radHappyNo);

        borderCenter.add(jPanel6);

        chbSecured.setText("Secured");
        chbSecured.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chbSecuredMouseClicked(evt);
            }
        });
        jPanel7.add(chbSecured);

        btnDisplay.setText("Display");
        btnDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDisplayMouseClicked(evt);
            }
        });
        jPanel7.add(btnDisplay);

        borderCenter.add(jPanel7);

        formWrapper.add(borderCenter, java.awt.BorderLayout.CENTER);

        outerWrapper.add(formWrapper);

        textAreaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Output Area"));
        textAreaPanel.setLayout(new javax.swing.BoxLayout(textAreaPanel, javax.swing.BoxLayout.LINE_AXIS));

        outputArea.setEditable(false);
        outputArea.setColumns(20);
        outputArea.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        textAreaPanel.add(jScrollPane1);

        outerWrapper.add(textAreaPanel);

        miFile.setMnemonic('F');
        miFile.setText("File");

        miFileNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        miFileNew.setText("New");
        miFileNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFileNewActionPerformed(evt);
            }
        });
        miFile.add(miFileNew);

        miFileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miFileOpen.setText("Open");
        miFileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFileOpenActionPerformed(evt);
            }
        });
        miFile.add(miFileOpen);
        miFile.add(jSeparator1);

        miFileClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        miFileClose.setText("Close");
        miFileClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFileCloseActionPerformed(evt);
            }
        });
        miFile.add(miFileClose);

        miFileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miFileSave.setText("Save");
        miFileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFileSaveActionPerformed(evt);
            }
        });
        miFile.add(miFileSave);
        miFile.add(jSeparator2);

        miFileAppExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        miFileAppExit.setText("Exit");
        miFileAppExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFileAppExitActionPerformed(evt);
            }
        });
        miFile.add(miFileAppExit);

        jMenuBar1.add(miFile);

        miEdit.setMnemonic('E');
        miEdit.setText("Edit");

        miEditCustomOutput.setText("Print To TextArea");

        miECOPrintHappy.setText("I'm Happy");
        miECOPrintHappy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miECOPrintHappyActionPerformed(evt);
            }
        });
        miEditCustomOutput.add(miECOPrintHappy);

        miECOPrintTemplate.setText("Form Data");

        miECOPTNameOnly.setText("Print Full Name Only");
        miECOPTNameOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miECOPTNameOnlyActionPerformed(evt);
            }
        });
        miECOPrintTemplate.add(miECOPTNameOnly);

        miECOPTAll.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        miECOPTAll.setText("Print All Form Data");
        miECOPTAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miECOPTAllActionPerformed(evt);
            }
        });
        miECOPrintTemplate.add(miECOPTAll);

        miEditCustomOutput.add(miECOPrintTemplate);

        miEdit.add(miEditCustomOutput);

        miEditFormToggle.setText("Form");

        miEFTCheckbox.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        miEFTCheckbox.setSelected(true);
        miEFTCheckbox.setText("Show Form");
        miEFTCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEFTCheckboxActionPerformed(evt);
            }
        });
        miEditFormToggle.add(miEFTCheckbox);

        miEFTClearOutput.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        miEFTClearOutput.setText("Clear Output");
        miEFTClearOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEFTClearOutputActionPerformed(evt);
            }
        });
        miEditFormToggle.add(miEFTClearOutput);

        miEdit.add(miEditFormToggle);

        miEditOutputControl.setText("TextArea Color");

        miEOCWhite.setText("White");
        miEOCWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEOCWhiteActionPerformed(evt);
            }
        });
        miEditOutputControl.add(miEOCWhite);

        miEOCGreen.setText("Dark Green");
        miEOCGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEOCGreenActionPerformed(evt);
            }
        });
        miEditOutputControl.add(miEOCGreen);

        miEOCGreyBlack.setText("Grey Black");
        miEOCGreyBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEOCGreyBlackActionPerformed(evt);
            }
        });
        miEditOutputControl.add(miEOCGreyBlack);

        miEdit.add(miEditOutputControl);

        jMenuBar1.add(miEdit);

        miAbout.setMnemonic('A');
        miAbout.setText("About");
        miAbout.setToolTipText("");

        miAboutShowDialog.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        miAboutShowDialog.setText("About");
        miAboutShowDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAboutShowDialogActionPerformed(evt);
            }
        });
        miAbout.add(miAboutShowDialog);

        jMenuBar1.add(miAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outerWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(outerWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisplayMouseClicked
        outputArea.setEnabled(true);
        String output = "\n";
        
        output += "\nFirst Name: " + txtFName.getText();
        output += "\nLast Name: " + txtLName.getText();
        output += (lstNationality.getSelectedValue() != null ? "\nNationality: "+lstNationality.getSelectedValue(): "");
        output += (!cmbSex.getSelectedItem().toString().equals("null")? "\nSex: "+cmbSex.getSelectedItem().toString(): "");
        
        for(Enumeration<AbstractButton> buttons = btnGrpHappy.getElements(); buttons.hasMoreElements();){
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                output += "\nHappy?: " + button.getText();
            }
        }
        
        outputArea.append(output);
    }//GEN-LAST:event_btnDisplayMouseClicked

    private void chbSecuredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chbSecuredMouseClicked
        txtFName.setEnabled(!chbSecured.isSelected());
        txtLName.setEnabled(!chbSecured.isSelected());
    }//GEN-LAST:event_chbSecuredMouseClicked

    private void miFileNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFileNewActionPerformed
        JOptionPane.showMessageDialog(
                this,
                "You have selected '" + miFileNew.getText() + "' action from File menu",
                "Message",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_miFileNewActionPerformed

    private void miFileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFileOpenActionPerformed
        JOptionPane.showMessageDialog(
                this,
                "You have selected '" + miFileOpen.getText() + "' action from File menu",
                "Message",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_miFileOpenActionPerformed

    private void miFileCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFileCloseActionPerformed
        JOptionPane.showMessageDialog(
                this,
                "You have selected '" + miFileClose.getText() + "' action from File menu",
                "Message",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_miFileCloseActionPerformed

    private void miFileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFileSaveActionPerformed
        JOptionPane.showMessageDialog(
                this,
                "You have selected '" + miFileSave.getText() + "' action from File menu",
                "Message",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_miFileSaveActionPerformed

    private void miFileAppExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFileAppExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_miFileAppExitActionPerformed

    private void miECOPrintHappyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miECOPrintHappyActionPerformed
        outputArea.setEnabled(true);
        outputArea.append("\nI'm Happy");
    }//GEN-LAST:event_miECOPrintHappyActionPerformed

    private void miECOPTNameOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miECOPTNameOnlyActionPerformed
        outputArea.setEnabled(true);
        outputArea.append(
                "\nFirst Name: " + txtFName.getText() +
                "\nLast Name: " + txtLName.getText()
        );
    }//GEN-LAST:event_miECOPTNameOnlyActionPerformed

    private void miECOPTAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miECOPTAllActionPerformed
        outputArea.setEnabled(true);
        String output = "\n";
        
        output += "\nFirst Name: " + txtFName.getText();
        output += "\nLast Name: " + txtLName.getText();
        output += (lstNationality.getSelectedValue() != null ? "\nNationality: "+lstNationality.getSelectedValue(): "");
        output += (!cmbSex.getSelectedItem().toString().equals("null")? "\nSex: "+cmbSex.getSelectedItem().toString(): "");
        
        for(Enumeration<AbstractButton> buttons = btnGrpHappy.getElements(); buttons.hasMoreElements();){
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                output += "\nHappy?: " + button.getText();
            }
        }
        
        outputArea.append(output);
    }//GEN-LAST:event_miECOPTAllActionPerformed

    private void miEFTCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEFTCheckboxActionPerformed
        formWrapper.setVisible(miEFTCheckbox.isSelected());
    }//GEN-LAST:event_miEFTCheckboxActionPerformed

    private void miEFTClearOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEFTClearOutputActionPerformed
        outputArea.setText("");
    }//GEN-LAST:event_miEFTClearOutputActionPerformed

    private void miEOCGreyBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEOCGreyBlackActionPerformed
        outputArea.setBackground(new Color(69,73,74));
        outputArea.setForeground(new Color(187,187,187));
    }//GEN-LAST:event_miEOCGreyBlackActionPerformed

    private void miEOCGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEOCGreenActionPerformed
        outputArea.setBackground(new Color(25, 63, 27));
        outputArea.setForeground(new Color(187,187,187));
    }//GEN-LAST:event_miEOCGreenActionPerformed

    private void miEOCWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEOCWhiteActionPerformed
        outputArea.setBackground(new Color(205, 205, 205));
        outputArea.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_miEOCWhiteActionPerformed

    private void miAboutShowDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAboutShowDialogActionPerformed
        
        String aboutText = "This is a rewritten version of an earlier submission."
                + "\nFeaturing more panels, use of layouts, and a much cleaner look and feel"
                + "\nThis program uses the FlatLAF Look and Feel with the Darcula Theme"
                + "\nIcons from jIconFont seems to be incompatible, but this does look a lot cleaner."
                + "\n\nCreated by Baz Ian Gil De Guzman (12-CPROG-A)" 
                + "\nFinished ~11 PM, May 27 2021";
        
        JOptionPane.showMessageDialog(
                this,
                aboutText,
                "About Program",
                JOptionPane.INFORMATION_MESSAGE
        );
    }//GEN-LAST:event_miAboutShowDialogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
            try {
                javax.swing.UIManager.setLookAndFeel( new FlatDarculaLaf() );
            } catch( Exception ex ) {
                System.err.println( "Failed to initialize LaF" );
            }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel borderCenter;
    private javax.swing.JButton btnDisplay;
    private javax.swing.ButtonGroup btnGrpHappy;
    private javax.swing.JCheckBox chbSecured;
    private javax.swing.JComboBox<String> cmbSex;
    private javax.swing.JPanel formWrapper;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblHappy;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblNationality;
    private javax.swing.JLabel lblSex;
    private javax.swing.JList<String> lstNationality;
    private javax.swing.JMenu miAbout;
    private javax.swing.JMenuItem miAboutShowDialog;
    private javax.swing.JMenuItem miECOPTAll;
    private javax.swing.JMenuItem miECOPTNameOnly;
    private javax.swing.JMenuItem miECOPrintHappy;
    private javax.swing.JMenu miECOPrintTemplate;
    private javax.swing.JCheckBoxMenuItem miEFTCheckbox;
    private javax.swing.JMenuItem miEFTClearOutput;
    private javax.swing.JMenuItem miEOCGreen;
    private javax.swing.JMenuItem miEOCGreyBlack;
    private javax.swing.JMenuItem miEOCWhite;
    private javax.swing.JMenu miEdit;
    private javax.swing.JMenu miEditCustomOutput;
    private javax.swing.JMenu miEditFormToggle;
    private javax.swing.JMenu miEditOutputControl;
    private javax.swing.JMenu miFile;
    private javax.swing.JMenuItem miFileAppExit;
    private javax.swing.JMenuItem miFileClose;
    private javax.swing.JMenuItem miFileNew;
    private javax.swing.JMenuItem miFileOpen;
    private javax.swing.JMenuItem miFileSave;
    private javax.swing.JPanel outerWrapper;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JRadioButton radHappyNo;
    private javax.swing.JRadioButton radHappyYes;
    private javax.swing.JPanel textAreaPanel;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    // End of variables declaration//GEN-END:variables
}
