/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.formdev.flatlaf.FlatDarculaLaf;
import controller.ItemController;
import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;
import model.Item;

/**
 *
 * @author bigjo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    
    private ItemController ic = new ItemController();
    public Main() {
        initComponents();

        CardLayout cl = (CardLayout) pnl_FormWrapper.getLayout();
        cl.show(pnl_FormWrapper, "Default");
        //Hide components that are not immediately needed.
        pnl_FormWrapper.setVisible(false);
        btn_AddItem.setVisible(false);
        btn_EditItem.setVisible(false);
        btn_DeleteItem.setVisible(false);
        
        //Components that are completely invisible, i.e, <hidden> input in HTML forms.
        pnlEdit_oldItemName.setVisible(false);
        
        TableDataLoader.fillItemTable(jtbl_Items, ic);
        

    }
    
    private void toggleFormPanel(){
        String action = btn_ToggleForms.getActionCommand();
        
        switch(action){
            case "View Forms":
                
                btn_ToggleForms.setActionCommand("Hide Forms");
                btn_ToggleForms.setText("Hide Forms");
                pnl_FormWrapper.setVisible(true);
                
                btn_AddItem.setVisible(true);
                btn_EditItem.setVisible(true);
                btn_DeleteItem.setVisible(true);
                
                break;
                
            case "Hide Forms":
                
                btn_ToggleForms.setActionCommand("View Forms");
                btn_ToggleForms.setText("View Forms");
                pnl_FormWrapper.setVisible(false);
                
                btn_AddItem.setVisible(false);
                btn_EditItem.setVisible(false);
                btn_DeleteItem.setVisible(false);
                
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_WindowWrapper = new javax.swing.JPanel();
        pnl_TableWindowWrapper = new javax.swing.JPanel();
        pnl_ItemsTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_Items = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btn_ToggleForms = new javax.swing.JButton();
        btn_SearchItem = new javax.swing.JButton();
        btn_SearchItemByName = new javax.swing.JButton();
        btn_EditItem = new javax.swing.JButton();
        btn_AddItem = new javax.swing.JButton();
        btn_DeleteItem = new javax.swing.JButton();
        pnl_FormWrapper = new javax.swing.JPanel();
        pnl_FormDefault = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_DeleteItem = new javax.swing.JPanel();
        pnlDelete_label = new javax.swing.JLabel();
        pnlDelete_lbl_Delete = new javax.swing.JLabel();
        pnlDelete_btn_Confirm = new javax.swing.JButton();
        pnlDelete_btn_Cancel = new javax.swing.JButton();
        pnl_EditItem = new javax.swing.JPanel();
        pnlEdit_ErrorLabel = new javax.swing.JLabel();
        pnlEdit_lbl_Name = new javax.swing.JLabel();
        pnlEdit_inputName = new javax.swing.JTextField();
        pnlEdit_lbl_Quantity = new javax.swing.JLabel();
        pnlEdit_lbl_Price = new javax.swing.JLabel();
        pnlEdit_inputPrice = new javax.swing.JSpinner();
        pnlEdit_inputQty = new javax.swing.JSpinner();
        pnlEdit_btn_Save = new javax.swing.JButton();
        pnlEdit_btn_cancel = new javax.swing.JButton();
        pnlEdit_inputID = new javax.swing.JTextField();
        pnlEdit_lbl_ID = new javax.swing.JLabel();
        pnlEdit_oldItemName = new javax.swing.JLabel();
        pnl_AddItem = new javax.swing.JPanel();
        pnlAdd_label = new javax.swing.JLabel();
        pnlAdd_lbl_Name = new javax.swing.JLabel();
        pnlAdd_inputName = new javax.swing.JTextField();
        pnlAdd_lbl_Qty = new javax.swing.JLabel();
        pnlAdd_inputQty = new javax.swing.JSpinner();
        pnlAdd_lbl_Price = new javax.swing.JLabel();
        pnlAdd_inputPrice = new javax.swing.JSpinner();
        pnlAdd_btn_Save = new javax.swing.JButton();
        pnlAdd_btn_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnl_WindowWrapper.setLayout(new java.awt.GridLayout(1, 0));

        pnl_TableWindowWrapper.setBorder(javax.swing.BorderFactory.createTitledBorder("Items Table"));
        pnl_TableWindowWrapper.setLayout(new java.awt.BorderLayout());

        pnl_ItemsTable.setLayout(new java.awt.BorderLayout());

        jtbl_Items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "name", "quantity", "price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbl_Items.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtbl_Items);
        if (jtbl_Items.getColumnModel().getColumnCount() > 0) {
            jtbl_Items.getColumnModel().getColumn(0).setResizable(false);
            jtbl_Items.getColumnModel().getColumn(1).setResizable(false);
            jtbl_Items.getColumnModel().getColumn(2).setResizable(false);
            jtbl_Items.getColumnModel().getColumn(3).setResizable(false);
        }

        pnl_ItemsTable.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Buttons"));

        btn_ToggleForms.setText("View Forms");
        btn_ToggleForms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ToggleFormsActionPerformed(evt);
            }
        });
        jPanel5.add(btn_ToggleForms);

        btn_SearchItem.setText("Search by ID");
        btn_SearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchItemActionPerformed(evt);
            }
        });
        jPanel5.add(btn_SearchItem);

        btn_SearchItemByName.setText("Search by Name");
        btn_SearchItemByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchItemByNameActionPerformed(evt);
            }
        });
        jPanel5.add(btn_SearchItemByName);

        btn_EditItem.setText("Edit Item");
        btn_EditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EditItemActionPerformed(evt);
            }
        });
        jPanel5.add(btn_EditItem);

        btn_AddItem.setText("Add Item");
        btn_AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddItemActionPerformed(evt);
            }
        });
        jPanel5.add(btn_AddItem);

        btn_DeleteItem.setText("Delete Item");
        btn_DeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteItemActionPerformed(evt);
            }
        });
        jPanel5.add(btn_DeleteItem);

        pnl_ItemsTable.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        pnl_TableWindowWrapper.add(pnl_ItemsTable, java.awt.BorderLayout.CENTER);

        pnl_WindowWrapper.add(pnl_TableWindowWrapper);

        getContentPane().add(pnl_WindowWrapper);

        pnl_FormWrapper.setBorder(javax.swing.BorderFactory.createTitledBorder("Form"));
        pnl_FormWrapper.setMaximumSize(new java.awt.Dimension(438, 562));
        pnl_FormWrapper.setMinimumSize(new java.awt.Dimension(438, 562));
        pnl_FormWrapper.setLayout(new java.awt.CardLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>\n<h1> Item Control Forms </h1>\n<h2> Use the buttons below the Items Table to continue </h2>\n</html>");

        javax.swing.GroupLayout pnl_FormDefaultLayout = new javax.swing.GroupLayout(pnl_FormDefault);
        pnl_FormDefault.setLayout(pnl_FormDefaultLayout);
        pnl_FormDefaultLayout.setHorizontalGroup(
            pnl_FormDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_FormDefaultLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        pnl_FormDefaultLayout.setVerticalGroup(
            pnl_FormDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_FormDefaultLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        pnl_FormWrapper.add(pnl_FormDefault, "Default");

        pnl_DeleteItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Delete Item"));

        pnlDelete_label.setText("<html><h1>Delete Item</h1></html>");

        pnlDelete_lbl_Delete.setText("<html><h2>Confirm Delete?</h2></html>");

        pnlDelete_btn_Confirm.setText("<html><h2>Yes</h2></html>");
        pnlDelete_btn_Confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnlDelete_btn_ConfirmActionPerformed(evt);
            }
        });

        pnlDelete_btn_Cancel.setText("<html><h2>Cancel</h2></html>");
        pnlDelete_btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnlDelete_btn_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_DeleteItemLayout = new javax.swing.GroupLayout(pnl_DeleteItem);
        pnl_DeleteItem.setLayout(pnl_DeleteItemLayout);
        pnl_DeleteItemLayout.setHorizontalGroup(
            pnl_DeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_DeleteItemLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(pnl_DeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_DeleteItemLayout.createSequentialGroup()
                        .addComponent(pnlDelete_btn_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlDelete_btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlDelete_lbl_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDelete_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147))
        );
        pnl_DeleteItemLayout.setVerticalGroup(
            pnl_DeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_DeleteItemLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(pnlDelete_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(pnlDelete_lbl_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(pnl_DeleteItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlDelete_btn_Confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDelete_btn_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pnl_FormWrapper.add(pnl_DeleteItem, "Delete");

        pnl_EditItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit Item"));

        pnlEdit_ErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlEdit_ErrorLabel.setText("<html><h1>Edit Item</h1></html>");

        pnlEdit_lbl_Name.setText("<html><h2>Name:</h2></html>");

        pnlEdit_lbl_Quantity.setText("<html><h2>Quantity:</h2></html>");

        pnlEdit_lbl_Price.setText("<html><h2>Price</h2></html>");

        pnlEdit_inputPrice.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));

        pnlEdit_inputQty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        pnlEdit_btn_Save.setText("<html><h2>Save</h2></html>");
        pnlEdit_btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnlEdit_btn_SaveActionPerformed(evt);
            }
        });

        pnlEdit_btn_cancel.setText("<html><h2>Cancel</h2></html>");
        pnlEdit_btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnlEdit_btn_cancelActionPerformed(evt);
            }
        });

        pnlEdit_inputID.setEditable(false);
        pnlEdit_inputID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pnlEdit_lbl_ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlEdit_lbl_ID.setText("ID");

        javax.swing.GroupLayout pnl_EditItemLayout = new javax.swing.GroupLayout(pnl_EditItem);
        pnl_EditItem.setLayout(pnl_EditItemLayout);
        pnl_EditItemLayout.setHorizontalGroup(
            pnl_EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_EditItemLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(pnl_EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_EditItemLayout.createSequentialGroup()
                        .addComponent(pnlEdit_ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_EditItemLayout.createSequentialGroup()
                        .addGroup(pnl_EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_EditItemLayout.createSequentialGroup()
                                .addComponent(pnlEdit_lbl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlEdit_inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_EditItemLayout.createSequentialGroup()
                                .addComponent(pnlEdit_lbl_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlEdit_inputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_EditItemLayout.createSequentialGroup()
                                .addComponent(pnlEdit_lbl_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlEdit_inputQty, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_EditItemLayout.createSequentialGroup()
                                .addComponent(pnlEdit_btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlEdit_btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(128, 128, 128))))
            .addGroup(pnl_EditItemLayout.createSequentialGroup()
                .addGroup(pnl_EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_EditItemLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(pnl_EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlEdit_lbl_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlEdit_inputID, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)))
                    .addGroup(pnl_EditItemLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(pnlEdit_oldItemName)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_EditItemLayout.setVerticalGroup(
            pnl_EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_EditItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEdit_oldItemName)
                .addGap(1, 1, 1)
                .addComponent(pnlEdit_ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlEdit_lbl_ID)
                .addGap(2, 2, 2)
                .addComponent(pnlEdit_inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlEdit_lbl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlEdit_inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlEdit_lbl_Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlEdit_inputQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlEdit_lbl_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlEdit_inputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnl_EditItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlEdit_btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlEdit_btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pnl_FormWrapper.add(pnl_EditItem, "Edit");

        pnl_AddItem.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Item"));

        pnlAdd_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlAdd_label.setText("<html><h1>Add Item</h1></html>");

        pnlAdd_lbl_Name.setText("<html><h2>Name:</h2></html>");

        pnlAdd_lbl_Qty.setText("<html><h2>Quantity:</h2></html>");

        pnlAdd_inputQty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        pnlAdd_lbl_Price.setText("<html><h2>Price:</h2></html>");

        pnlAdd_inputPrice.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));

        pnlAdd_btn_Save.setText("Save");
        pnlAdd_btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnlAdd_btn_SaveActionPerformed(evt);
            }
        });

        pnlAdd_btn_Cancel.setText("Cancel");
        pnlAdd_btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnlAdd_btn_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_AddItemLayout = new javax.swing.GroupLayout(pnl_AddItem);
        pnl_AddItem.setLayout(pnl_AddItemLayout);
        pnl_AddItemLayout.setHorizontalGroup(
            pnl_AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AddItemLayout.createSequentialGroup()
                .addGroup(pnl_AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_AddItemLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(pnlAdd_label, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_AddItemLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(pnl_AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlAdd_lbl_Qty)
                            .addComponent(pnlAdd_lbl_Price)
                            .addComponent(pnlAdd_lbl_Name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pnlAdd_inputName)
                            .addComponent(pnlAdd_inputQty, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(pnlAdd_inputPrice)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_AddItemLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlAdd_btn_Save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlAdd_btn_Cancel)
                        .addGap(28, 28, 28)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        pnl_AddItemLayout.setVerticalGroup(
            pnl_AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_AddItemLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(pnlAdd_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(pnl_AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlAdd_lbl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAdd_inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnl_AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlAdd_lbl_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAdd_inputQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnl_AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlAdd_lbl_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAdd_inputPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(pnl_AddItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlAdd_btn_Save)
                    .addComponent(pnlAdd_btn_Cancel))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pnl_FormWrapper.add(pnl_AddItem, "Add");

        getContentPane().add(pnl_FormWrapper);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ToggleFormsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ToggleFormsActionPerformed
        toggleFormPanel();
    }//GEN-LAST:event_btn_ToggleFormsActionPerformed

    private void btn_EditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EditItemActionPerformed

        String[] s = TableDataLoader.getSelectedRow(jtbl_Items);
        
        if(s == null){
            JOptionPane.showMessageDialog(this, "No Selected Row");
            return;
        }
        
        CardLayout cl = (CardLayout) pnl_FormWrapper.getLayout();
        cl.show(pnl_FormWrapper, "Edit");
        
        Map<String, Integer> m = TableDataLoader.getTableColumnMap(jtbl_Items);
        
        //Set an invisible Label which holds the user's name
        pnlEdit_oldItemName.setText(s[m.get("name")]);
        
        pnlEdit_inputName.setText(s[m.get("name")]);
        pnlEdit_inputID.setText(s[m.get("id")]);
            
            double n1 = Double.parseDouble(s[m.get("quantity")]);
            double n2 = Double.parseDouble(s[m.get("price")]);
        pnlEdit_inputQty.setValue(n1);
        pnlEdit_inputPrice.setValue(n2);
        
    }//GEN-LAST:event_btn_EditItemActionPerformed

    private void btn_AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddItemActionPerformed
        CardLayout cl = (CardLayout) pnl_FormWrapper.getLayout();
        cl.show(pnl_FormWrapper, "Add");
        
    }//GEN-LAST:event_btn_AddItemActionPerformed

    private void btn_DeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteItemActionPerformed
        String[] s = TableDataLoader.getSelectedRow(jtbl_Items);
        
        if(s == null){
            JOptionPane.showMessageDialog(this, "No Selected Row");
            return;
        }
        
        CardLayout cl = (CardLayout) pnl_FormWrapper.getLayout();
        cl.show(pnl_FormWrapper, "Delete");

    }//GEN-LAST:event_btn_DeleteItemActionPerformed

    private void btn_SearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchItemActionPerformed
        String id = JOptionPane.showInputDialog(this, "Enter Product ID: ");
        
        Item result = null;
        try{
            result = ic.viewItemById(Integer.parseInt(id));
        } catch(Exception ex){
            System.out.println("Search Item Failed, given ID is not an integer");
        }
        
        if(result == null){
            JOptionPane.showMessageDialog(this, "This Item ID does not exist");
            return;
        }
        
        Map<String, Integer> m = TableDataLoader.getMapOfColAndRowID(jtbl_Items, 0);
        int targetRow = m.get(id);
        System.out.println("Selected Row ID: " + targetRow);
        jtbl_Items.setRowSelectionInterval(targetRow, targetRow);
    }//GEN-LAST:event_btn_SearchItemActionPerformed

    private void btn_SearchItemByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchItemByNameActionPerformed
        String name = JOptionPane.showInputDialog(this, "Enter Item Name: ");
        
        Item result = ic.viewItemByName(name);
        
        if(result == null){
            JOptionPane.showMessageDialog(this, "This Item ("+name+") does not exist");
            return;
        }
        
        Map<String, Integer> m = TableDataLoader.getMapOfColAndRowID(jtbl_Items, 0);
        int targetRow = m.get(Integer.toString(result.getId()));
        jtbl_Items.setRowSelectionInterval(targetRow, targetRow);
        
    }//GEN-LAST:event_btn_SearchItemByNameActionPerformed

    private void pnlEdit_btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnlEdit_btn_cancelActionPerformed
        
        pnlEdit_inputName.setText("");
        pnlEdit_inputPrice.setValue(0);
        pnlEdit_inputQty.setValue(0);
        toggleFormPanel();
        jtbl_Items.clearSelection();
        
        TableDataLoader.fillItemTable(jtbl_Items, ic);
    }//GEN-LAST:event_pnlEdit_btn_cancelActionPerformed

    private void pnlEdit_btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnlEdit_btn_SaveActionPerformed
        
        
        String t0 = pnlEdit_inputName.getText();
        String t1 = pnlEdit_inputQty.getValue().toString();
        String t2 = pnlEdit_inputPrice.getValue().toString();
        //System.out.println("QTY: " + t1 + "\tPRICE: " + t2);
        
        Item i = ic.viewItemByName(t0);
        
        //Use an invisible label component to verify that the item name is not changed.
        if(i != null && !t0.equals(pnlEdit_oldItemName.getText())){
            JOptionPane.showMessageDialog(this, "This item name ("+t0+") is already registered");
            return;
        }
        
        ic.editItem(new Item(
                t0,
                (int) Double.parseDouble(t1), //Cannot directly parse Int from string `1.0`, weak.
                Double.parseDouble(t2)
            ), Integer.parseInt(pnlEdit_inputID.getText())
        );
        
        TableDataLoader.fillItemTable(jtbl_Items, ic);
    }//GEN-LAST:event_pnlEdit_btn_SaveActionPerformed

    private void pnlAdd_btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnlAdd_btn_CancelActionPerformed
        
        pnlAdd_inputName.setText("");
        pnlAdd_inputQty.setValue(0);
        pnlAdd_inputPrice.setValue(0);
        toggleFormPanel();
        jtbl_Items.clearSelection();
        
        TableDataLoader.fillItemTable(jtbl_Items, ic);
    }//GEN-LAST:event_pnlAdd_btn_CancelActionPerformed

    private void pnlAdd_btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnlAdd_btn_SaveActionPerformed
        
        String in1 = pnlAdd_inputName.getText();
        String in2 = pnlAdd_inputQty.getValue().toString();
        String in3 = pnlAdd_inputPrice.getValue().toString();
        
        if (in1.equals("")) {
            JOptionPane.showMessageDialog(this, "Item Name field is empty");
            return;
        }
        
        if (ic.viewItemByName(in1) != null) {
            JOptionPane.showMessageDialog(this, "This Item name ("+in1+") is already registered");
            return;
        }
        
        ic.addItem(new Item(
                in1, (int) Double.parseDouble(in2), Double.parseDouble(in3)
        ));
        
        TableDataLoader.fillItemTable(jtbl_Items, ic);
    }//GEN-LAST:event_pnlAdd_btn_SaveActionPerformed

    private void pnlDelete_btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnlDelete_btn_CancelActionPerformed
        pnlDelete_lbl_Delete.setText("<html><h2>Confirm Delete?</h2></html>");
        toggleFormPanel();
        jtbl_Items.clearSelection();
        
        TableDataLoader.fillItemTable(jtbl_Items, ic);
    }//GEN-LAST:event_pnlDelete_btn_CancelActionPerformed

    private void pnlDelete_btn_ConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnlDelete_btn_ConfirmActionPerformed
        String[] s = TableDataLoader.getSelectedRow(jtbl_Items);
        
        Map<String, Integer> m = TableDataLoader.getTableColumnMap(jtbl_Items);
        pnlDelete_lbl_Delete.setText("<html><h2>Delete Item ID "+s[m.get("id")]+"? </h2></html>");
        int itemId = Integer.parseInt(s[m.get("id")]);
            System.out.println("Apparent Item ID: " + itemId);
        ic.deleteItem(itemId);
        toggleFormPanel();
        TableDataLoader.fillItemTable(jtbl_Items, ic);
    }//GEN-LAST:event_pnlDelete_btn_ConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel( new FlatDarculaLaf() );
        } catch( UnsupportedLookAndFeelException ex ) {
            System.err.println( "Failed to initialize LaF" + ex );
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddItem;
    private javax.swing.JButton btn_DeleteItem;
    private javax.swing.JButton btn_EditItem;
    private javax.swing.JButton btn_SearchItem;
    private javax.swing.JButton btn_SearchItemByName;
    private javax.swing.JButton btn_ToggleForms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbl_Items;
    private javax.swing.JButton pnlAdd_btn_Cancel;
    private javax.swing.JButton pnlAdd_btn_Save;
    private javax.swing.JTextField pnlAdd_inputName;
    private javax.swing.JSpinner pnlAdd_inputPrice;
    private javax.swing.JSpinner pnlAdd_inputQty;
    private javax.swing.JLabel pnlAdd_label;
    private javax.swing.JLabel pnlAdd_lbl_Name;
    private javax.swing.JLabel pnlAdd_lbl_Price;
    private javax.swing.JLabel pnlAdd_lbl_Qty;
    private javax.swing.JButton pnlDelete_btn_Cancel;
    private javax.swing.JButton pnlDelete_btn_Confirm;
    private javax.swing.JLabel pnlDelete_label;
    private javax.swing.JLabel pnlDelete_lbl_Delete;
    private javax.swing.JLabel pnlEdit_ErrorLabel;
    private javax.swing.JButton pnlEdit_btn_Save;
    private javax.swing.JButton pnlEdit_btn_cancel;
    private javax.swing.JTextField pnlEdit_inputID;
    private javax.swing.JTextField pnlEdit_inputName;
    private javax.swing.JSpinner pnlEdit_inputPrice;
    private javax.swing.JSpinner pnlEdit_inputQty;
    private javax.swing.JLabel pnlEdit_lbl_ID;
    private javax.swing.JLabel pnlEdit_lbl_Name;
    private javax.swing.JLabel pnlEdit_lbl_Price;
    private javax.swing.JLabel pnlEdit_lbl_Quantity;
    private javax.swing.JLabel pnlEdit_oldItemName;
    private javax.swing.JPanel pnl_AddItem;
    private javax.swing.JPanel pnl_DeleteItem;
    private javax.swing.JPanel pnl_EditItem;
    private javax.swing.JPanel pnl_FormDefault;
    private javax.swing.JPanel pnl_FormWrapper;
    private javax.swing.JPanel pnl_ItemsTable;
    private javax.swing.JPanel pnl_TableWindowWrapper;
    private javax.swing.JPanel pnl_WindowWrapper;
    // End of variables declaration//GEN-END:variables
}
