/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.awt.Color;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import mdlaf.*;
import jiconfont.swing.*;
import jiconfont.icons.google_material_design_icons.*;

/**
 *
 * @author bigjo
 */
public class form extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupHappy = new javax.swing.ButtonGroup();
        wrapperPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldOutput = new javax.swing.JTextArea();
        inputPanel = new javax.swing.JPanel();
        dropdownGender = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listNationality = new javax.swing.JList<>();
        fldFName = new javax.swing.JTextField();
        labelGender = new javax.swing.JLabel();
        fldLName = new javax.swing.JTextField();
        labelLName = new javax.swing.JLabel();
        radioHappyNo = new javax.swing.JRadioButton();
        btnDisplay = new javax.swing.JButton();
        labelNationality = new javax.swing.JLabel();
        checkSecured = new javax.swing.JCheckBox();
        radioHappyYes = new javax.swing.JRadioButton();
        labelHappy = new javax.swing.JLabel();
        labelFName = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileMenuNew = new javax.swing.JMenuItem();
        fileMenuOpen = new javax.swing.JMenuItem();
        fileMenuClose = new javax.swing.JMenuItem();
        fileMenuSave = new javax.swing.JMenuItem();
        fileMenuExit = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        editMenuPrintToTextArea = new javax.swing.JMenu();
        editMenuPrintHappy = new javax.swing.JMenuItem();
        editMenuCustomPrint = new javax.swing.JMenu();
        editMenuPrintName = new javax.swing.JMenuItem();
        editMenuPrintAll = new javax.swing.JMenuItem();
        editMenuFormControl = new javax.swing.JMenu();
        editMenuToggleFormVIsible = new javax.swing.JCheckBoxMenuItem();
        editMenuTextAreaControl = new javax.swing.JMenu();
        editMenuTextAreaToWhite = new javax.swing.JMenuItem();
        editMenuTextAreaToGreen = new javax.swing.JMenuItem();
        AboutMenu = new javax.swing.JMenu();
        aboutMenuShowDialog = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fieldOutput.setColumns(20);
        fieldOutput.setRows(5);
        fieldOutput.setEnabled(false);
        jScrollPane1.setViewportView(fieldOutput);

        dropdownGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Prefer not to say" }));

        listNationality.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Filipino", "Japanese", "American", "British", "Korean", "Brazilian" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listNationality);

        labelGender.setText("Gender");

        labelLName.setText("Last Name");

        btnGroupHappy.add(radioHappyNo);
        radioHappyNo.setText("No");

        btnDisplay.setText("Display");
        btnDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDisplayMouseClicked(evt);
            }
        });

        labelNationality.setText("Nationality");

        checkSecured.setText("Secured");
        checkSecured.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkSecuredMouseClicked(evt);
            }
        });

        btnGroupHappy.add(radioHappyYes);
        radioHappyYes.setText("Yes");

        labelHappy.setText("Are you happy?");

        labelFName.setText("First Name");

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelHappy, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelFName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(checkSecured)
                    .addComponent(radioHappyNo)
                    .addComponent(fldFName)
                    .addComponent(fldLName)
                    .addComponent(dropdownGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioHappyYes)
                    .addComponent(jScrollPane2)
                    .addComponent(btnDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFName)
                    .addComponent(fldFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLName)
                    .addComponent(fldLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNationality)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGender)
                    .addComponent(dropdownGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHappy)
                    .addComponent(radioHappyYes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioHappyNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkSecured)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDisplay)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout wrapperPanelLayout = new javax.swing.GroupLayout(wrapperPanel);
        wrapperPanel.setLayout(wrapperPanelLayout);
        wrapperPanelLayout.setHorizontalGroup(
            wrapperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        wrapperPanelLayout.setVerticalGroup(
            wrapperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wrapperPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wrapperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                    .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        fileMenu.setText("File");

        fileMenuNew.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.NOTE_ADD, 24));
        fileMenuNew.setText("New");
        fileMenuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuNewActionPerformed(evt);
            }
        });
        fileMenu.add(fileMenuNew);

        fileMenuOpen.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.FOLDER_OPEN, 24));
        fileMenuOpen.setText("Open");
        fileMenuOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuOpenActionPerformed(evt);
            }
        });
        fileMenu.add(fileMenuOpen);

        fileMenuClose.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.CLOSE, 24) );
        fileMenuClose.setText("Close");
        fileMenuClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuCloseActionPerformed(evt);
            }
        });
        fileMenu.add(fileMenuClose);

        fileMenuSave.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.SAVE, 24));
        fileMenuSave.setText("Save");
        fileMenuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuSaveActionPerformed(evt);
            }
        });
        fileMenu.add(fileMenuSave);

        fileMenuExit.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.EXIT_TO_APP, 24));
        fileMenuExit.setText("Exit");
        fileMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuExitActionPerformed(evt);
            }
        });
        fileMenu.add(fileMenuExit);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        editMenuPrintToTextArea.setText("Print to Text Area");

        editMenuPrintHappy.setText("I'm Happy");
        editMenuPrintHappy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuPrintHappyActionPerformed(evt);
            }
        });
        editMenuPrintToTextArea.add(editMenuPrintHappy);

        editMenuCustomPrint.setText("Form Data");

        editMenuPrintName.setText("Print Name Only");
        editMenuPrintName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuPrintNameActionPerformed(evt);
            }
        });
        editMenuCustomPrint.add(editMenuPrintName);

        editMenuPrintAll.setText("Print All Form Data");
        editMenuPrintAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuPrintAllActionPerformed(evt);
            }
        });
        editMenuCustomPrint.add(editMenuPrintAll);

        editMenuPrintToTextArea.add(editMenuCustomPrint);

        editMenu.add(editMenuPrintToTextArea);

        editMenuFormControl.setText("Form");

        editMenuToggleFormVIsible.setSelected(true);
        editMenuToggleFormVIsible.setText("Show Form");
        editMenuToggleFormVIsible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuToggleFormVIsibleActionPerformed(evt);
            }
        });
        editMenuFormControl.add(editMenuToggleFormVIsible);

        editMenu.add(editMenuFormControl);

        editMenuTextAreaControl.setText("Text Area Color");

        editMenuTextAreaToWhite.setText("White");
        editMenuTextAreaToWhite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuTextAreaToWhiteActionPerformed(evt);
            }
        });
        editMenuTextAreaControl.add(editMenuTextAreaToWhite);

        editMenuTextAreaToGreen.setText("Green");
        editMenuTextAreaToGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuTextAreaToGreenActionPerformed(evt);
            }
        });
        editMenuTextAreaControl.add(editMenuTextAreaToGreen);

        editMenu.add(editMenuTextAreaControl);

        menuBar.add(editMenu);

        AboutMenu.setText("About");

        aboutMenuShowDialog.setIcon(IconFontSwing.buildIcon(GoogleMaterialDesignIcons.INFO, 24));
        aboutMenuShowDialog.setText("About");
        aboutMenuShowDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuShowDialogActionPerformed(evt);
            }
        });
        AboutMenu.add(aboutMenuShowDialog);

        menuBar.add(AboutMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wrapperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wrapperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisplayMouseClicked

        //Uncomment to clear field every mouse click
        //fieldOutput.setText("");
        fieldOutput.setEnabled(true);
        String output = "\n";
        
        //First Name
        output += "First Name: " + fldFName.getText() + "\n";
        
        //Last Name
        output += "Last Name: " + fldLName.getText() + "\n";
        
        //Nationality
        output += "Nationality: " + listNationality.getSelectedValue() + "\n";
        
        //Gender
        output += "Gender: " + dropdownGender.getSelectedItem().toString() + "\n";
        
        //Button Group
        for(Enumeration<AbstractButton> buttons = btnGroupHappy.getElements(); buttons.hasMoreElements();){
            AbstractButton button = buttons.nextElement();
            
            if(button.isSelected()){
                output += "Happy: " + button.getText() + "\n";
            }
        }
        
        //Display
        fieldOutput.append(output);
        
    }//GEN-LAST:event_btnDisplayMouseClicked

    private void checkSecuredMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkSecuredMouseClicked
        //fieldOutput.setEnabled(!checkSecured.isSelected());
        fldFName.setEnabled(!checkSecured.isSelected());
        fldLName.setEnabled(!checkSecured.isSelected());
    }//GEN-LAST:event_checkSecuredMouseClicked

    private void editMenuPrintHappyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuPrintHappyActionPerformed
        fieldOutput.setEnabled(true);
        fieldOutput.append("\nI'm Happy\n");
    }//GEN-LAST:event_editMenuPrintHappyActionPerformed

    private void editMenuPrintNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuPrintNameActionPerformed
        fieldOutput.setEnabled(true);
        
        String output = "";
        
        //First Name
        output += "First Name: " + fldFName.getText() + "\n";
        
        //Last Name
        output += "Last Name: " + fldLName.getText() + "\n";
        
        fieldOutput.append(output);
    }//GEN-LAST:event_editMenuPrintNameActionPerformed

    private void editMenuPrintAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuPrintAllActionPerformed
        fieldOutput.setEnabled(true);
        String output = "\n";
        
        //First Name
        output += "First Name: " + fldFName.getText() + "\n";
        
        //Last Name
        output += "Last Name: " + fldLName.getText() + "\n";
        
        //Nationality
        output += "Nationality: " + listNationality.getSelectedValue() + "\n";
        
        //Gender
        output += "Gender: " + dropdownGender.getSelectedItem().toString() + "\n";
        
        //Button Group
        for(Enumeration<AbstractButton> buttons = btnGroupHappy.getElements(); buttons.hasMoreElements();){
            AbstractButton button = buttons.nextElement();
            
            if(button.isSelected()){
                output += "Happy: " + button.getText() + "\n";
            }
        }
        
        //Display
        fieldOutput.append(output);
    }//GEN-LAST:event_editMenuPrintAllActionPerformed

    private void editMenuToggleFormVIsibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuToggleFormVIsibleActionPerformed
        
        inputPanel.setVisible(editMenuToggleFormVIsible.isSelected());
        
    }//GEN-LAST:event_editMenuToggleFormVIsibleActionPerformed

    private void editMenuTextAreaToWhiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuTextAreaToWhiteActionPerformed
        fieldOutput.setBackground(new Color(240,240,240));
    }//GEN-LAST:event_editMenuTextAreaToWhiteActionPerformed

    private void editMenuTextAreaToGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuTextAreaToGreenActionPerformed
        fieldOutput.setBackground(Color.GREEN);
    }//GEN-LAST:event_editMenuTextAreaToGreenActionPerformed

    private void fileMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_fileMenuExitActionPerformed

    private void aboutMenuShowDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuShowDialogActionPerformed

        JOptionPane.showMessageDialog(
            this,
            "About program",
            "About",
            JOptionPane.INFORMATION_MESSAGE,
            IconFontSwing.buildIcon(GoogleMaterialDesignIcons.INFO, 48)
        );
    }//GEN-LAST:event_aboutMenuShowDialogActionPerformed

    private void fileMenuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuNewActionPerformed
        JOptionPane.showMessageDialog(this, "You have selected 'New' from the File Menu Options");
    }//GEN-LAST:event_fileMenuNewActionPerformed

    private void fileMenuOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuOpenActionPerformed
        JOptionPane.showMessageDialog(this, "You have selected 'Open' from the File Menu Options");
    }//GEN-LAST:event_fileMenuOpenActionPerformed

    private void fileMenuCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuCloseActionPerformed
        JOptionPane.showMessageDialog(this, "You have selected 'Close' from the File Menu Options");
    }//GEN-LAST:event_fileMenuCloseActionPerformed

    private void fileMenuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuSaveActionPerformed
        JOptionPane.showMessageDialog(this, "You have selected 'Save' from the File Menu Options");
    }//GEN-LAST:event_fileMenuSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }

           try{
                javax.swing.UIManager.setLookAndFeel(new MaterialLookAndFeel());
            } catch (javax.swing.UnsupportedLookAndFeelException ex){
                java.util.logging.Logger.getLogger(form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AboutMenu;
    private javax.swing.JMenuItem aboutMenuShowDialog;
    private javax.swing.JButton btnDisplay;
    private javax.swing.ButtonGroup btnGroupHappy;
    private javax.swing.JCheckBox checkSecured;
    private javax.swing.JComboBox<String> dropdownGender;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu editMenuCustomPrint;
    private javax.swing.JMenu editMenuFormControl;
    private javax.swing.JMenuItem editMenuPrintAll;
    private javax.swing.JMenuItem editMenuPrintHappy;
    private javax.swing.JMenuItem editMenuPrintName;
    private javax.swing.JMenu editMenuPrintToTextArea;
    private javax.swing.JMenu editMenuTextAreaControl;
    private javax.swing.JMenuItem editMenuTextAreaToGreen;
    private javax.swing.JMenuItem editMenuTextAreaToWhite;
    private javax.swing.JCheckBoxMenuItem editMenuToggleFormVIsible;
    private javax.swing.JTextArea fieldOutput;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fileMenuClose;
    private javax.swing.JMenuItem fileMenuExit;
    private javax.swing.JMenuItem fileMenuNew;
    private javax.swing.JMenuItem fileMenuOpen;
    private javax.swing.JMenuItem fileMenuSave;
    private javax.swing.JTextField fldFName;
    private javax.swing.JTextField fldLName;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelFName;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelHappy;
    private javax.swing.JLabel labelLName;
    private javax.swing.JLabel labelNationality;
    private javax.swing.JList<String> listNationality;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JRadioButton radioHappyNo;
    private javax.swing.JRadioButton radioHappyYes;
    private javax.swing.JPanel wrapperPanel;
    // End of variables declaration//GEN-END:variables
}
