/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;

/**
 *
 * @author bigjo
 */
public class EditUserPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditUserPanel
     */
    public EditUserPanel() {
        initComponents();
    }
    
    class VerifyIntegerInput extends InputVerifier{
        public boolean verify(JComponent input){
            JFormattedTextField ftf = (JFormattedTextField) input;
            boolean valid = false;
            try{
                int num = Integer.parseInt(ftf.getText());
                valid = true;
            } catch (Exception e){
                valid = false;
            }
            
            return valid;
        }
    }
    
    protected final int INPUT_NAME = 0;
    protected final int INPUT_AGE = 1;
    protected final int INPUT_ADDRESS = 2;
    
    protected void setUserFields(String[] dataArray){
        lblId.setText("User ID: "+dataArray[0]);
        txtName.setText(dataArray[1]);
        txtfAge.setText(dataArray[2]);
        txtAddress.setText(dataArray[3]);
    }
    protected void setUserId(String id){
        lblId.setText("User ID: "+id);
    } 
    
    protected void setUserName(String name){
        txtName.setText(name);
    }
    
    protected void setUserAge(String age){
        txtfAge.setText(age);
    }
    
    protected void setUserAddress(String address){
        txtAddress.setText(address);
    }
    
    protected Object[] getUserFields(){
        return new Object[]{
            txtName.getText(),
            txtfAge.getText(),
            txtAddress.getText()
        };
    }
    protected String getUserName(){
        return txtName.getText();
    }
    
    protected String getUserAge(){
        return txtfAge.getText();
    }
    
    protected String getUserAddress(){
        return txtAddress.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtfAge = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Name");

        lblId.setText("User ID: null");

        jLabel3.setText("Age");

        jLabel4.setText("Address");

        txtfAge.setInputVerifier(new VerifyIntegerInput());

        jLabel2.setText("Notice: Age must be a number");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAddress)
                    .addComponent(txtName)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JFormattedTextField txtfAge;
    // End of variables declaration//GEN-END:variables
}
